setup:
	ssh root@vps242864.ovh.net
up:
	scp index.html Toolbox.js GenLap.js DisplayLap.js root@vps242864.ovh.net:/var/www/html
img:
	scp images/background.jpg root@vps242864.ovh.net:/var/www/html/images
