setup:
	ssh root@vps242864.ovh.net
up:
	scp index.html Toolbox.js GenLap.js DisplayLap.js GUI.js style.css root@vps242864.ovh.net:/var/www/html
img:
	scp images/background.jpg images/logo.png root@vps242864.ovh.net:/var/www/html/images
